# 출력층 설계 (Output layer)

In [1]:
!pip3 install torch torchvision torchaudio

### 소프트맥스 오버플로우 방지

In [2]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def stable_softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

X = np.array([1000, 1001, 1002])

print(softmax(X))
print(stable_softmax(X))

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


C:\Users\Playdata\AppData\Local\Temp\ipykernel_26524\1488661191.py:4: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
C:\Users\Playdata\AppData\Local\Temp\ipykernel_26524\1488661191.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x)


### - pytorch 라이브러리 함수 사용

In [10]:
import torch
import torch.nn.functional as F

x = torch.tensor([1000, 1001, 1002], dtype=torch.float32)
print(x.dtype)

softmax_output = F.softmax(x, dim=0)    # dim: softmax를 적용할 축
print(softmax_output)

sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

torch.float32
tensor([0.0900, 0.2447, 0.6652])
tensor([1., 1., 1.])


### 손실함수와 연계

In [13]:
import torch
import torch.nn as nn
import torch.optim as optim

In [23]:
# 간단한 다중 클래스 분류 모델 정의 (입력 값 : 5개, 출력: 3 클래스)
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5, 3)

    def forward(self, x):
        return self.fc(x)
    
model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4, 5)
labels = torch.tensor([0, 2, 1, 0])

for _ in range(50):
    outputs = model(inputs)             # 순전파
    loss = criterion(outputs, labels)   # 손실 계산
    print(loss.item())

    optimizer.zero_grad()           # 이전 단계에서 계산된 기울기를 0으로 초기화
    loss.backward()                 # 손실에 대한 역전파 수행 (파라미터에 대한 기울기 계산)
    optimizer.step()                # 계산된 기울기를 사용하여 옵티마이저가 모델의 파라미터 업데이트

0.7260336875915527
0.6982700824737549
0.6714045405387878
0.6454434394836426
0.6203894019126892
0.5962416529655457
0.5729958415031433
0.5506441593170166
0.5291755199432373
0.5085752010345459
0.4888256788253784
0.46990665793418884
0.4517955183982849
0.4344673454761505
0.4178958237171173
0.40205344557762146
0.38691195845603943
0.3724428415298462
0.3586178123950958
0.34540894627571106
0.33278903365135193
0.3207317590713501
0.3092119097709656
0.2982052266597748
0.28768861293792725
0.27764004468917847
0.2680385708808899
0.258864164352417
0.2500976324081421
0.24172088503837585
0.23371626436710358
0.22606712579727173
0.21875745058059692
0.21177169680595398
0.20509521663188934
0.19871363043785095
0.19261331856250763
0.1867811232805252
0.1812044084072113
0.17587102949619293
0.17076927423477173
0.16588813066482544
0.16121678054332733
0.15674498677253723
0.15246301889419556
0.14836138486862183
0.14443130791187286
0.1406642198562622
0.13705195486545563
0.1335868388414383
