### ndarray 연산

In [2]:
import numpy as np

In [10]:
arr_a = np.arange(1, 10).reshape(3, 3)
arr_b = np.full_like(arr_a, 3)
print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [24]:
# 덧셈
print(arr_a + arr_b)
print(np.add(arr_a, arr_b))


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [22]:
# 뺼셈
print(arr_a - arr_b)
print(np.subtract(arr_a, arr_b))

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [25]:
# 곱셈
print(arr_a * arr_b)
print(np.multiply(arr_a, arr_b))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [26]:
# 나눗셈
print(arr_a / arr_b)
print(np.divide(arr_a, arr_b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# 특수연산 1: 거듭제곱
print(arr_a ** arr_b)
print(np.power(arr_a, arr_b))
print(np.square(arr_a, arr_b)) # 제곱

[[                   1                   16                19683]
 [          4294967296   298023223876953125 -5108087961858080768]
 [ 6812400838176574343                    0  8677311020002933897]]
[[                   1                   16                19683]
 [          4294967296   298023223876953125 -5108087961858080768]
 [ 6812400838176574343                    0  8677311020002933897]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [34]:
# 특수연산 2: 몫
print(arr_a // arr_b)
print(np.floor_divide(arr_a, arr_b))

[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
# 특수연산 3: 나머지
print(arr_a % arr_b)
print(np.mod(arr_a, arr_b))

[[0 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
# 제곱근
print(np.sqrt(arr_a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [7]:
sales_q1 = np.array([200, 340, 150, 400])
sales_q2 = np.array([220, 300, 180, 420])

print(sales_q1 + sales_q2)

print((sales_q1 + sales_q2) /2)


[420 640 330 820]
[210. 320. 165. 410.]


In [39]:
first = [200, 340, 150, 400]
second = [220, 300, 180, 420]

total = sum(first) + sum(second)
print(total)
print(total/4)

2210
552.5


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [42]:

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


---

### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [15]:
arr_a = np.arange(1, 10).reshape(3, 3)
arr_b = np.full_like(arr_a, 3)

result_arr = arr_a * np.array([[5, 5, 5],[5, 5, 5],[5, 5, 5]]) # (3, 3)
result_arr = arr_a * np.array([5, 5, 5]) #(3, )
result_arr = arr_a * np.array([5]) #(1, )
result_arr = arr_a * 5 # 스칼라값

result_arr 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
arr2 = np.array([5, 10, 100])            # (3, )

arr1 + arr2

array([[  6,  12, 103],
       [  9,  15, 106]])

In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([[100], [200]]) # (2, 1)

arr1 + arr2

array([[101, 102, 103],
       [204, 205, 206]])

In [20]:
arr1 = np.array([1, 2, 3])        # (3, )
arr2 = np.array([[4], [5], [6]])  # (3, 1)
print(arr2.shape, arr2.shape)
print(arr1 + arr2)                # (3, 3)

(3, 1) (3, 1)
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [23]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([1, 2]) # (2, )

print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 곱셈은 첫 번째 행렬 A의 행과 두 번쨰 행렬 B의 열 간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 행의 수가 같아야 한다.
    - 연산 결관의 shape은 (첫 번째 행렬A의 행수, 두 번째 행렬 B의 열수)이다.

In [28]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 * arr2)
print(arr1.shape, arr2.shape, (arr1*arr2).shape)

print(np.dot(arr1, arr2))
print(np.dot(arr1, arr2).shape)

[[ 5 12]
 [21 32]]
(2, 2) (2, 2) (2, 2)
[[19 22]
 [43 50]]
(2, 2)


In [38]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8], [9, 10], [11, 12]])
arr3.shape, arr4.shape
print(np.dot(arr3, arr4)) # (2, 3) * (3, 2) => (2, 2)
print(np.dot(arr4, arr3)) # (3, 2) * (2, 3) => (3, 3)

[[ 58  64]
 [139 154]]
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [39]:
# (100, 20000) (20000, 100) : (100, 100)
# (20000, 1000) (100, 20000) : (20000, 20000)
# (100, 20000) (100, 20000) : (2, ) : 내적 안됨

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# @
# print(arr @ arr)

# .T
print(arr)
print("---------")
print(arr.T)  #  arr.T = arr의 전치행렬 (행-열을 교환)
print("---------")
print(arr @ arr.T)
print("---------")
#matmul()
print(np.matmul(arr, arr.T))

[[1 2 3]
 [4 5 6]]
---------
[[1 4]
 [2 5]
 [3 6]]
---------
[[14 32]
 [32 77]]
---------
[[14 32]
 [32 77]]


다음 두 배열 간의 내적 연산을 수행하세요.

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1, arr2))

32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [51]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(np.add(arr2d, arr1d))

[[11 22 33]
 [14 25 36]]


---

### 연산 함수 및 집계 함수

In [52]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [53]:
# 절대값

np.abs(arr_negative)

array([[  1,   2],
       [100, 200]])

In [56]:
# 올림/ 반올림
print(np.ceil(arr_float))
print(np.round(arr_float))
print(np.round(arr_float, 2))

[[ 2.  6.]
 [ 8. 11.]]
[[ 1.  6.]
 [ 8. 10.]]
[[ 1.23  5.68]
 [ 7.89 10.12]]


In [59]:
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])

# 내림
print(np.floor(arr_float))

# 버림 (절삭)
print(np.trunc(arr_float))

[[ 1.  5.]
 [ 7. 10.]]
[[ 1.  5.]
 [ 7. 10.]]


In [63]:
print(arr)
print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0)) # 행 기준 (행을 고정하고, 같은 열에서 가장 큰 값)
print(np.min(arr, axis=1)) # 열 기준 (열을 고정하고, 같은 행에서 가장 작은 값)

[[1 2 3]
 [4 5 6]]
6
1
[4 5 6]
[1 4]


In [71]:
# 합계
print(arr.sum())  #axis=Npne
print(np.sum(arr))

print(arr)
print(arr.sum(axis=0))  # 행 기준 (행방향 덧셈)
print(arr.sum(axis=1))  # 열 기준 (열 방향 덧셈)


21
21
[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [72]:
print(arr.mean())
print(np.mean(arr))

print(arr.mean(axis=0))
print(arr.mean(axis=1))


3.5
3.5
[2.5 3.5 4.5]
[2. 5.]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

In [77]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 20])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.average(arr))

[30 40 50]
150
50
10
30.0
