### ndarray 정렬

In [1]:
import numpy as np

##### 1차원 배열 정렬

In [7]:
arr = np.random.randint(1, 11, 10)
arr


array([5, 4, 1, 1, 5, 1, 2, 9, 5, 9], dtype=int32)

In [8]:
# np.sort(arr) : 정렬된 ndarray를 반환

print(np.sort(arr))
print(arr)

[1 1 1 2 4 5 5 5 9 9]
[5 4 1 1 5 1 2 9 5 9]


In [9]:
np.sort(arr)[::-1]

array([9, 9, 5, 5, 5, 4, 2, 1, 1, 1], dtype=int32)

---

##### 2차원 배열 정렬

In [11]:
arr = np.random.randint(10, size=(3, 4)) # 0 이상 10 미만
arr

array([[4, 9, 8, 6],
       [5, 0, 7, 6],
       [6, 0, 9, 1]], dtype=int32)

In [14]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[4 0 7 1]
 [5 0 8 6]
 [6 9 9 6]]
[[4 6 8 9]
 [0 5 6 7]
 [0 1 6 9]]


In [16]:
print(np.sort(arr, axis=None))
print(np.sort(arr, axis=None).shape)

[0 0 1 4 5 6 6 6 7 8 9 9]
(12,)


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

In [17]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

print(np.sort(arr2d, axis=1))
print(np.sort(arr2d, axis=0))

[[3 5 8]
 [1 2 9]]
[[2 3 1]
 [8 9 5]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

In [ ]:
arr = np.array([15, 10, 20])

print(np.sort)