### ndarray 형태 변경

In [2]:
import numpy as np

In [10]:
# reshape()
# 요소의 개수와 맞는 shape이어야 함
arr = np.arange(12)
print(arr.ndim, arr)
print("---------------")

print(arr.reshape(3, 4))
print(arr.ndim, arr)
print("---------------")

arr = arr.reshape(3, 4)
arr = arr.reshape(6, 2)
arr = arr.reshape(1, 12)
arr = arr.reshape(2, 2, 3)
# arr = arr.reshape(2, 7)
print(arr.ndim, arr.shape)
print("---------------")
print(arr)

1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
---------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
---------------
3 (2, 2, 3)
---------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [12]:
# reshape() -> -1
arr = arr.reshape(-1)
print(arr)

# -1인 축은 자동 계산
arr = arr.reshape(4, -1)
arr = arr.reshape(-1, 4)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
# np.ravel()
arr = np.arange(50).reshape(5, 10)
print(arr)
print(np.ravel(arr))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [22]:
# np.expand_dims()
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)

print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=0).shape)

print(np.expand_dims(arr_1d, axis=1).shape)


arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.shape, arr_2d)

print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=0).shape)

print(np.expand_dims(arr_2d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
(10, 1)
(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
(1, 2, 2)
(2, 1, 2)


In [26]:
# np,squeese() : 차원의 값이 1일 때 제거 
arr = np.array([[1, 2]])
print(arr.shape)

arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr, axis=0)
print(arr2.shape)

(1, 2)
(2,)
