## ndarray indexing & slicing

In [3]:
import numpy as np

In [3]:
arr = np.arange(1, 11)
print(arr)
print(arr[1], arr[3], arr[9])

[ 1  2  3  4  5  6  7  8  9 10]
2 4 10


In [22]:
arr = np.arange(1, 11)

# print(arr)
print(arr[2:7])
print(arr[0:9:2])
print(arr[4:11])
print(arr[0:7])
print(arr[::-1])

[3 4 5 6 7]
[1 3 5 7 9]
[ 5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[10  9  8  7  6  5  4  3  2  1]


In [33]:
# 2차원 배열 슬라이싱

arr = np.array([[10, 20, 30], [40, 50, 60],[70, 80, 90]])
# print(arr)

# print(arr[0:2, 1:2]) # [행 슬라이싱 , 열 슬라이싱]

# print(arr[0:2])

# print(arr[:, 1:3])

# 슬라이싱 = shape 유지 (차원 유지지)
print(arr[:-1, 0:1], arr[:-2, 0:1].shape)

# index 접근 -> 값을 꺼내서 반환 (차원 제거)
print(arr[:-1, 0], arr[:-2, 0:1].shape)

[[10]
 [40]] (1, 1)
[10 40] (1, 1)


In [38]:
#  1차원 배열 fancy indexing
arr = np.arange(5, 31, 5)
print(arr)
print(arr[[1, 3, 5]])

indices = [1, 3, 5]
print(arr[indices])

[ 5 10 15 20 25 30]
[10 20 30]
[10 20 30]


In [56]:
# 2차원 배열 fancy indexing

arr = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60],
])

print(arr[0][1], arr[1][2])

indices1 = [0, 1]
indices2 = [1, 2]
indicess = (indices1, indices2)


print(arr[[0, 1], [1, 2]])

10 35
[10 35]


In [59]:
# boolean indexing
arr = np.arange(1, 6)

bools = [True, False, False, False, True]
print(arr[bools])

[1 5]


In [62]:
# 2차원 배열 boolean indexing
arr = np.array([
    [3, 6, 9],
    [12, 15, 18],
    [21, 24, 27]
])

print(arr[arr > 10])
print(arr[arr % 2 == 0])


[12 15 18 21 24 27]
[ 6 12 18 24]


In [64]:
arr = np.array([10, 20, 30, 40, 50])
is_all_positive = np.all(arr > 0)

if is_all_positive:
    print('모든 수는 양수 입니다.')
else:
    print('모든 수가 양수는 아닙니다.')

모든 수는 양수 입니다.


np.all() : ndarray의 모든 요소가 조건을 만족할떄 True 반환

np.any() : ndarray의 하나라도 조건을 만족할떄 True 반환

In [65]:
has_positive = np.all(arr > 0)

if has_positive:
    print('양수가 포함되어 있습니다다')
else:
    print('모든 수가 음수입니다.')

양수가 포함되어 있습니다다


---

실습

아래 배열에서 인덱싱과 슬라이싱을 사용하여 다음 작업을 수행하세요.

1. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
2. 배열 `arr`에서 1번째 열만 추출
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [11]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[1:2, 2:3])

print("---답안---")
print(arr[1, 2])

print("---")
print("---")
print(arr[:, 0:1])
print("---답안---")

print(arr[:, 0])
print("---")
print("---")
print(arr[0:1, 0:2])
print("---")

print(arr[0:2, 0:2])
print("---")

[[60]]
---답안---
60
---
---
[[10]
 [40]
 [70]]
---답안---
[10 40 70]
---
---
[[10 20]]
---
[[10 20]
 [40 50]]
---


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [16]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

arr1 = arr[0:5:2]
print(arr1)

print("---답안---")
list = [0, 2, 4]
print(arr[list])
print(arr[[0, 2, 4]])

print("------")
print(arr[arr > 50])
print("---답안---")



[10 30 50]
---답안---
[10 30 50]
[10 30 50]
------
[60 70]
---답안---


In [17]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [54]:
print(sales[sales >= 200])

print("----")
# print(sales[:,2:3])
third = sales[:,2:3]
# print(third <= 100)
print(sales[3:4, :2])
print("----")

second = sales[:, 1:2]
# print(second)
# print(second >= 150)
bools = second >= 150
lists = []
a = 0

for i in bools:
    if i:
        # print(i)
        # print(sales[a])
        a += 1
        lists.append(sales[a])

for list in lists:
    print(list)


[200 220 300 320 310]
----
[[50 45]]
----
[ 80  90 110]
[200 180 220]
[50 45 70]


In [52]:
print(sales[sales[:, 2] <= 100, 0:2])

[[120 150]
 [ 50  45]]


In [59]:
print(sales[sales[:, 1] >= 150, :])

[[120 150 100]
 [200 180 220]
 [300 320 310]]
